### ISSUE TITLE
class name change

### ISSUE THREAD

**Issue by donald-john** [SpiderStrategies/draggable-list#18]
changing class names from `draggable-list` to `list-draggable` to go better with the SB3 naming convention.

**Comment by mattsgarlata** [comment]
Oh, I'm not sure if I thought this one through enough. Since the component is called draggable-list, I think we should probably just leave the CSS class name as draggable-list rather than calling it list-draggable.

**Comment by nathanbowser** [comment]
@donald-john pinged me on slack and I didn't think of that either.

**Comment by nathanbowser** [comment]
So, I agree @mattsgarlata

**Comment by donald-john** [comment]
Ok cool I'll close this out then
