### ISSUE TITLE
Don't trigger drags when selecting text in inputs and textareas

### ISSUE THREAD

**Issue by mattsgarlata** [SpiderStrategies/draggable-list#23]
Here I have some controls in a draggable list. If I attempt to edit the text, a drag starts. I think the event listeners for the draggable list shouldn't fire when dragging inside an input box or textarea. Here's a video to show what I mean:

https://user-images.githubusercontent.com/1598200/165133331-0329bdc0-8088-4dd2-9a8a-66732f13b457.mov

It seems to me like this change should go in the draggable-list component, but please LMK if you disagree Nathan.

This isn't very high priority. We can tackle it in June after the feature freeze.

**Comment by nathanbowser** [comment]
@mattsgarlata Try giving those elements a class of `draggable-list-nodrag` and see if that works for you.

See https://github.com/SpiderStrategies/draggable-list/pull/19

**Comment by mattsgarlata** [comment]
Oh, I forgot about that. That totally does the trick
